🏗️ feat: many dotfiles changes for compatibility with devcontainers

diff --git a/bin/beep b/bin/beep
--- a/bin/beep
+++ b/bin/beep
@@ -1,9 +1,71 @@
 #!/usr/bin/env bash
-set -euf -o pipefail
+# shellcheck disable=SC2034
 
-if [ $DISTRO == "macos" ]; then
+set -Eeuo pipefail
+trap cleanup SIGINT SIGTERM ERR EXIT
+
+usage() {
+  cat <<EOF
+Usage: $(basename "${BASH_SOURCE[0]}") [-h] [-v]
+
+Uses macOS "say" to say the word beep three times.
+
+Available options:
+
+-h, --help      Print this help and exit
+-v, --verbose   Print script debug info
+EOF
+  exit
+}
+
+cleanup() {
+  trap - SIGINT SIGTERM ERR EXIT
+}
+
+setup_colors() {
+  if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
+    NOFORMAT='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m' BLUE='\033[0;34m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
+  else
+    NOFORMAT='' RED='' GREEN='' ORANGE='' BLUE='' PURPLE='' CYAN='' YELLOW=''
+  fi
+}
+
+msg() {
+  echo >&2 -e "${1-}"
+}
+
+die() {
+  local msg=$1
+  local code=${2-1} # default exit status 1
+  msg "$msg"
+  exit "$code"
+}
+
+parse_params() {
+  while :; do
+    case "${1-}" in
+    -h | --help) usage ;;
+    -v | --verbose) set -x ;;
+    --no-color) NO_COLOR=1 ;;
+    -?*) die "Unknown option: $1" ;;
+    *) break ;;
+    esac
+    shift
+  done
+
+  args=("$@")
+
+  return 0
+}
+
+parse_params "$@"
+setup_colors
+
+if [ "$DISTRO" == "macos" ]; then
   say 'beep, beep, beep'
 else
-  echo "Can only beep on macOS"
-  exit 1
+  die "Can only beep on macOS"
 fi
+
+msg "${RED}Read parameters:${NOFORMAT}"
+msg "- arguments: ${args[*]-}"
diff --git a/bin/git-churn b/bin/git-churn
--- a/bin/git-churn
+++ b/bin/git-churn
@@ -1,6 +1,4 @@
 #!/usr/bin/env bash
-set -euf -o pipefail
-
 #
 # Written by Corey Haines
 # Scriptified by Gary Bernhardt
@@ -29,6 +27,24 @@ set -euf -o pipefail
 #
 # (These are all standard arguments to `git log`.)
 
+set -Eeuo pipefail
+trap cleanup SIGINT SIGTERM ERR EXIT
+
+cleanup() {
+  trap - SIGINT SIGTERM ERR EXIT
+}
+
+msg() {
+  echo >&2 -e "${1-}"
+}
+
+die() {
+  local msg=$1
+  local code=${2-1} # default exit status 1
+  msg "$msg"
+  exit "$code"
+}
+
 if command -v git 2>/dev/null; then
   git log \
       --all \
@@ -38,6 +54,5 @@ if command -v git 2>/dev/null; then
       --format='format:' "$@" \
       | sort | grep --invert-match '^$' | uniq -c | sort --numeric-sort
 else
-  echo "Git is not installed..."
-  exit 1
+  die "Git is not installed"
 fi
diff --git a/bin/git-divergence b/bin/git-divergence
--- a/bin/git-divergence
+++ b/bin/git-divergence
@@ -1,23 +1,38 @@
 #!/usr/bin/env bash
-set -euf -o pipefail
+
+set -Eeuo pipefail
+trap cleanup SIGINT SIGTERM ERR EXIT
+
+cleanup() {
+  trap - SIGINT SIGTERM ERR EXIT
+}
+
+msg() {
+  echo >&2 -e "${1-}"
+}
+
+die() {
+  local msg=$1
+  local code=${2-1} # default exit status 1
+  msg "$msg"
+  exit "$code"
+}
 
 if ! command -v git 2>/dev/null; then
-  echo "Git is not installed..."
-  exit 1
+  die "Git is not installed"
 fi
 
 (
   function branch() {
-    git branch 2>/dev/null | grep --regexp='^*' | tr -d '\* '
+    git branch 2>/dev/null | grep --regexp='^*' | tr --delete '\* '
   }
 
   function ensure_valid_ref() {
     ref=$1
     (
-      git show-ref $ref > /dev/null
+      git show-ref "$ref" > /dev/null
       if [[ $? == 1 ]]; then
-        echo "$0: bad ref: $ref"
-        exit 1
+        die "$0: bad ref: $ref"
       fi
     )
   }
@@ -25,13 +40,13 @@ fi
   function show_rev() {
     rev=$1
     git log \
-        --max-count=1 $rev \
-        --graph \
-        --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' \
-        --abbrev-commit \
-        --date=relative
+      --max-count=1 "$rev" \
+      --graph \
+      --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' \
+      --abbrev-commit \
+      --date=relative
     echo
-    git di $rev^..$rev | diffstat
+    git di "$rev^..$rev" | diffstat
     echo
   }
 
@@ -39,29 +54,29 @@ fi
     LOCAL=$1
     REMOTE=$2
   elif [[ $# == 1 ]]; then
-    LOCAL=`branch`
+    LOCAL=$(branch)
     REMOTE=$1
   else
-    LOCAL=`branch`
+    LOCAL=$(branch)
     REMOTE=origin/$LOCAL
   fi
 
-  ensure_valid_ref $LOCAL
-  ensure_valid_ref $REMOTE
+  ensure_valid_ref "$LOCAL"
+  ensure_valid_ref "$REMOTE"
 
-  echo "changes from local ${LOCAL} to remote ${REMOTE}:"
+  msg "changes from local ${LOCAL} to remote ${REMOTE}:"
   echo
 
-  echo incoming:
+  msg incoming:
   echo
-  for rev in `git rev-list $LOCAL..$REMOTE`; do
-    show_rev $rev
+  for rev in $(git rev-list "$LOCAL..$REMOTE"); do
+    show_rev "$rev"
   done
 
   echo
   echo outgoing:
   echo
-  for rev in `git rev-list $REMOTE..$LOCAL`; do
-    show_rev $rev
+  for rev in $(git rev-list "$REMOTE..$LOCAL"); do
+    show_rev "$rev"
   done
 ) | less --raw-control-chars
diff --git a/bin/git-goodness b/bin/git-goodness
--- a/bin/git-goodness
+++ b/bin/git-goodness
@@ -1,9 +1,25 @@
 #!/usr/bin/env bash
-set -euf -o pipefail
+
+set -Eeuo pipefail
+trap cleanup SIGINT SIGTERM ERR EXIT
+
+cleanup() {
+  trap - SIGINT SIGTERM ERR EXIT
+}
+
+msg() {
+  echo >&2 -e "${1-}"
+}
+
+die() {
+  local msg=$1
+  local code=${2-1} # default exit status 1
+  msg "$msg"
+  exit "$code"
+}
 
 if command -v git 2>/dev/null; then
-  git diff $* | gn
+  git diff "$@" | gn
 else
-  echo "Git is not installed..."
-  exit 1
+  die "Git is not installed"
 fi
diff --git a/bin/git-what-the-hell-just-happened b/bin/git-what-the-hell-just-happened
--- a/bin/git-what-the-hell-just-happened
+++ b/bin/git-what-the-hell-just-happened
@@ -1,25 +1,41 @@
 #!/usr/bin/env bash
-set -euf -o pipefail
+
+set -Eeuo pipefail
+trap cleanup SIGINT SIGTERM ERR EXIT
+
+cleanup() {
+  trap - SIGINT SIGTERM ERR EXIT
+}
+
+msg() {
+  echo >&2 -e "${1-}"
+}
+
+die() {
+  local msg=$1
+  local code=${2-1} # default exit status 1
+  msg "$msg"
+  exit "$code"
+}
 
 if ! command -v git 2>/dev/null; then
-  echo "Git is not installed..."
-  exit 1
+  die "Git is not installed"
 fi
 
 ref=${1:-"HEAD"}
 
-old=$ref@{1}
+old="$ref@{1}"
 new=$ref
 
 log() {
-  git log --graph --pretty=short --max-count=1 $1
+  git log --graph --pretty=short --max-count=1 "$1"
 }
 
-echo "Old revision:"
-log $old
+msg "Old revision:"
+log "$old"
 echo
-echo "New revision:"
-log $new
+msg "New revision:"
+log "$new"
 echo
-echo "Changes:"
-git diff --stat --summary $new $old
+msg "Changes:"
+git diff --stat --summary "$new" "$old"
diff --git a/bin/kopieid b/bin/kopieid
--- a/bin/kopieid
+++ b/bin/kopieid
@@ -1,17 +1,79 @@
 #!/usr/bin/env bash
-set -euf -o pipefail
+# shellcheck disable=SC2034
+
+set -Eeuo pipefail
+trap cleanup SIGINT SIGTERM ERR EXIT
+
+usage() {
+  cat <<EOF
+Usage: $(basename "${BASH_SOURCE[0]}") [-h] [-v] path_to_file
+
+Adds watermark to identification papers to prevent abuse.
+
+Available options:
+
+-h, --help      Print this help and exit
+-v, --verbose   Print script debug info
+EOF
+  exit
+}
+
+cleanup() {
+  trap - SIGINT SIGTERM ERR EXIT
+  # script cleanup here
+}
+
+setup_colors() {
+  if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
+    NOFORMAT='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m' BLUE='\033[0;34m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
+  else
+    NOFORMAT='' RED='' GREEN='' ORANGE='' BLUE='' PURPLE='' CYAN='' YELLOW=''
+  fi
+}
+
+msg() {
+  echo >&2 -e "${1-}"
+}
+
+die() {
+  local msg=$1
+  local code=${2-1} # default exit status 1
+  msg "$msg"
+  exit "$code"
+}
+
+parse_params() {
+  while :; do
+    case "${1-}" in
+    -h | --help) usage ;;
+    -v | --verbose) set -x ;;
+    --no-color) NO_COLOR=1 ;;
+    *) break ;;
+    esac
+    shift
+  done
+
+  args=("$@")
+
+  # check required params and arguments
+  [[ ${#args[@]} -eq 0 ]] && die "Missing script arguments"
+
+  return 0
+}
+
+parse_params "$@"
+setup_colors
 
 if ! command -v convert; then
-  echo "ImageMagick is required, exiting"
-  exit 1
+  die "ImageMagick is required, exiting"
 fi
 
-echo "Name of organisation?"
-read ORG
-echo "For what purpose can this organisation use this document?"
-read PURPOSE
+msg "Name of organisation?"
+read -r ORG
+msg "For what purpose can this organisation use this document?"
+read -r PURPOSE
 
-convert $1 \
+convert "$1" \
 \( -background none -pointsize 48 -fill "rgba(10,20,30,0.30)" label:"Copy for $ORG\nPurpose: $PURPOSE\nDate: $(date +'%Y-%m-%d')" -font Skia -rotate 20 -write mpr:tile +delete \) \
 \( +clone -tile mpr:tile -draw "color 0,0 reset" \) \
--compose over -composite -strip -interlace Plane -gaussian-blur 0.05 -quality 70% $1.watermarked.jpg
+-compose over -composite -strip -interlace Plane -gaussian-blur 0.05 -quality 70% "$1.watermarked.jpg"
