✨ feat: mostly changes to allow cross machine compatibility
A lot of things are now only loaded when the required binaries are in $PATH

diff --git a/bin/kopieid b/bin/kopieid
--- a/bin/kopieid
+++ b/bin/kopieid
@@ -1,6 +1,11 @@
 #!/usr/bin/env bash
 set -euf -o pipefail
 
+if ! command -v convert; then
+  echo "ImageMagick is required, exiting"
+  exit 1
+fi
+
 echo "Name of organisation?"
 read ORG
 echo "For what purpose can this organisation use this document?"
