🔒 feat: minimally safe maintenance script

diff --git a/bin/maintenance b/bin/maintenance
--- a/bin/maintenance
+++ b/bin/maintenance
@@ -1,19 +1,102 @@
 #!/usr/bin/env bash
-set -uf -o pipefail
 
+trap cleanup SIGINT SIGTERM ERR EXIT
+
+script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
+
+usage() {
+  cat <<EOF
+Gebruik: $(basename "${BASH_SOURCE[0]}") [-h] [-v] [-f] -p param_value arg1 [arg2...]
+
+Hier een beschrijving.
+
+Beschikbare opties:
+
+-h, --help      Print deze help en exit
+-v, --verbose   Print script debug info
+EOF
+  exit
+}
+
+cleanup() {
+  trap - SIGINT SIGTERM ERR EXIT
+  # script cleanup hier
+}
+
+setup_colors() {
+  if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
+    NOFORMAT='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m' BLUE='\033[0;34m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
+  else
+    NOFORMAT='' RED='' GREEN='' ORANGE='' BLUE='' PURPLE='' CYAN='' YELLOW=''
+  fi
+}
+
+msg() {
+  echo >&2 -e "${1-}"
+}
+
+die() {
+  local msg=$1
+  local code=${2-1} # default exit status 1
+  msg "$msg"
+  exit "$code"
+}
+
+parse_params() {
+  # defaultwaardes van parameters
+  flag=0
+  param=''
+
+  while :; do
+    case "${1-}" in
+    -h | --help) usage ;;
+    -v | --verbose) set -x ;;
+    --no-color) NO_COLOR=1 ;;
+    -f | --flag) flag=1 ;; # voorbeeld flag
+    -p | --param) # voorbeeld named parameter
+      param="${2-}"
+      shift
+      ;;
+    -?*) die "Onbekende optie: $1" ;;
+    *) break ;;
+    esac
+    shift
+  done
+
+  args=("$@")
+
+  return 0
+}
+
+parse_params "$@"
+setup_colors
+
+msg "${BLUE}Updating Mac App Store${NOFORMAT}"
 mas upgrade
+msg "${BLUE}Updating Homebrew${NOFORMAT}"
 brew update
+msg "${BLUE}Updating brews${NOFORMAT}"
 brew upgrade
+msg "${BLUE}Updating casks${NOFORMAT}"
 brew upgrade --cask
+msg "${BLUE}Cleaning Homebrew${NOFORMAT}"
 brew cleanup
+msg "${BLUE}Verifying Homebrew integrity${NOFORMAT}"
 brew doctor
+msg "${BLUE}Upgrading PECL packages${NOFORMAT}"
 pecl upgrade-all
+msg "${BLUE}Updating Composer packages${NOFORMAT}"
 composer global update
+msg "${BLUE}Updating tldr${NOFORMAT}"
 tldr --update
+msg "${GREEN}Applications to update manually${NOFORMAT}"
+brew list --cask -1 | xargs brew info --cask | rg auto_updates
+msg "adobe-creative-cloud (apps)"
+msg "steam (games)"
+msg "wipr (definitions)"
+msg "zprezto-update"
 
-echo "n**** Applications to update manually ****"
-brew list --cask -1 | xargs brew cask info | grep auto_updates
-echo "adobe-creative-cloud (apps)"
-echo "steam (games)"
-echo "wipr (definitions)"
-echo "zprezto-update"
+msg "${RED}Read parameters:${NOFORMAT}"
+msg "- flag: ${flag}"
+msg "- param: ${param}"
+msg "- arguments: ${args[*]-}"
