refactor(dotfiles): significant formatting changes

diff --git a/XDG_BIN_HOME/kopieid b/XDG_BIN_HOME/kopieid
--- a/XDG_BIN_HOME/kopieid
+++ b/XDG_BIN_HOME/kopieid
@@ -19,15 +19,28 @@ EOF
 
 cleanup() {
   trap - SIGINT SIGTERM ERR EXIT
-  # script cleanup here
 }
 
 setup_colors() {
   # shellcheck disable=SC2034
   if [[ -t 2 ]] && [[ -z "${NO_COLOR-}" ]] && [[ "${TERM-}" != "dumb" ]]; then
-    NOFORMAT='\033[0m' RED='\033[0;31m' GREEN='\033[0;32m' ORANGE='\033[0;33m' BLUE='\033[0;34m' PURPLE='\033[0;35m' CYAN='\033[0;36m' YELLOW='\033[1;33m'
+    readonly NOFORMAT='\033[0m'
+    readonly RED='\033[0;31m'
+    readonly GREEN='\033[0;32m'
+    readonly ORANGE='\033[0;33m'
+    readonly BLUE='\033[0;34m'
+    readonly PURPLE='\033[0;35m'
+    readonly CYAN='\033[0;36m'
+    readonly YELLOW='\033[1;33m'
   else
-    NOFORMAT='' RED='' GREEN='' ORANGE='' BLUE='' PURPLE='' CYAN='' YELLOW=''
+    readonly NOFORMAT=''
+    readonly RED=''
+    readonly GREEN=''
+    readonly ORANGE=''
+    readonly BLUE=''
+    readonly PURPLE=''
+    readonly CYAN=''
+    readonly YELLOW=''
   fi
 }
 
@@ -45,10 +58,10 @@ die() {
 parse_params() {
   while :; do
     case "${1-}" in
-    -h | --help) usage ;;
-    -v | --verbose) set -x ;;
-    --no-color) NO_COLOR=1 ;;
-    *) break ;;
+      -h | --help) usage ;;
+      -v | --verbose) set -x ;;
+      --no-color) NO_COLOR=1 ;;
+      *) break ;;
     esac
     shift
   done
@@ -64,9 +77,12 @@ parse_params() {
 parse_params "$@"
 setup_colors
 
-if ! command -v convert >/dev/null 2>&1; then
-  die "ImageMagick is required, exiting"
-fi
+required_binaries=("magick")
+for bin in "${required_binaries[@]}"; do
+  if ! command -v "$bin" >/dev/null 2>&1; then
+    die "$bin is required, exiting"
+  fi
+done
 
 msg "Name of organisation?"
 read -r ORG
